[build]
command = "npm install && node netlify-build.js"
publish = "out"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../build.js"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  CI = "true"
  NEXT_PUBLIC_SITE_URL = "https://mams.com.ng"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Primary domain configuration
[[redirects]]
  from = "http://mamsrealestate.netlify.app/*"
  to = "https://mams.com.ng/:splat"
  status = 301
  force = true

# Handle Next.js static assets
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# SSL Configuration
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
